# -*- coding: utf-8 -*-
# Generated by Django 1.11.11 on 2019-07-10 07:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OAuthUser',
            new_name='OAuthQQUser',
        ),
    ]
